# Custom Language File for Launcher Customizer

[ejs.app]
title = "Genesia Launcher"

[ejs.landing]
mediaGitHubURL = "https://github.com/Heristos/GenesiaLauncher"
mediaTwitterURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.gg/w8zFJAJc5b"

[ejs.settings]
sourceGithubLink = "https://github.com/Heristos/GenesiaLauncher"
supportLink = "https://github.com/Heristos/GenesiaLauncher/issues"

[ejs.welcome]
welcomeHeader = "BIENVENUE SUR GENESIA"
welcomeDescription = "Génésia est un serveur libre innovant, offrant une expérience de gameplay unique et inédite. Rejoignez-nous dès maintenant pour découvrir un monde où la liberté et la créativité sont au cœur de l'expérience."
welcomeDescCTA = "You are just a few clicks away from Westeros."
